############################################################################
# ESP32-P4 System Test Application
############################################################################

include $(APPDIR)/Make.defs

# Application name
PROGNAME  = esp32p4_system_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = EXAMPLES_ESP32P4_SYSTEM_TEST

# Source files
MAINSRC = esp32p4_system_test_main.c

include $(APPDIR)/Application.mk
