############################################################################
# ESP32-P4 GPIO Test Application
############################################################################

include $(APPDIR)/Make.defs

# Application name
PROGNAME  = esp32p4_gpio_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = EXAMPLES_ESP32P4_GPIO_TEST

# Source files
MAINSRC = esp32p4_gpio_test_main.c

include $(APPDIR)/Application.mk
