############################################################################
# ESP32-P4 UART Test Application
############################################################################

include $(APPDIR)/Make.defs

# Application name
PROGNAME  = esp32p4_uart_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = EXAMPLES_ESP32P4_UART_TEST

# Source files
MAINSRC = esp32p4_uart_test_main.c

include $(APPDIR)/Application.mk
